### ISSUE TITLE
Can't build after changing based_on path

### ISSUE THREAD

**Issue by pavelmaca** [zisismaras/marlin_auto_build#1]
I had tested exaple configuration, it worked fine.
After commiting my own configuration with different configuration path, build broke.

Changing `based_on.path` to `"/config/examples/Creality/Ender-3 Pro/CrealityV1/"` produce this error:

> checking builds for stable release
> [up-to-date] builds/ender3.js
> [build changed] builds/test.js
> checking builds for nightly release
> [up-to-date] builds/ender3.js
> [build changed] builds/test.js
> downloading stable 2.1.1
> building builds/test.js
> Command failed: cd ./dist/current_build &&             git clone -b release-2.1.1 https://github.com/MarlinFirmware/Configurations/ --depth 1 __build_configs &&             cp ./__build_configs//config/examples/Creality/Ender-3 Pro/CrealityV1//* ./Marlin
>         
> fatal: destination path '__build_configs' already exists and is not an empty directory.
> 
> Error: Process completed with exit code 1.
>

**Comment by zisismaras** [comment]
There was an issue with config paths having spaces in them. I just pushed a new release that fixes it.
You can update your workflow to use v1.0.13 and it should work.

Also note that 8-bit firmware files (`.hex` files like `CrealityV1`) are not currently supported. I might revisit this in the future but for now they will throw an error.
