### ISSUE TITLE
Only stable releases?

### ISSUE THREAD

**Issue by daniel-kukiela** [zisismaras/marlin_auto_build#2]
Hi,
First, thank you for this project, it helped me easily make firmware for someone who lives far away and I cannot help them directly :)
But I have a question: Is it possible to set it to only build from a stable branch? I don't seem to see a way to do so.
Thank you!

**Comment by zisismaras** [comment]
Hello, thanks a lot for your words!

There is an `only` option you can set to `"stable"` (or `"nightly"`) on the build file to build only a single branch.

```js
module.exports = {
    board_env: "STM32F103RE_creality",
    only: "stable",
    //rest of the file
}
```

**Comment by daniel-kukiela** [comment]
I must have missed it, haven't seen this option. Works like a charm. Thank you!
