### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by nbost130** [zisismaras/marlin_auto_build#3]
This is likely something obvious to an experienced developer. I've tried everything I can think of (adjusting permissions in yml, starting with a fresh repo, etc.) and I'm still getting this error "Invalid or unexpected token" It was working initially before I started building my .js files for desired builds. Started seeing this error during that process last night. Now all builds failing here. Thanks for any help!

---------------

Run cd marlin_auto_build && node ./lib/runner.js --color
  cd marlin_auto_build && node ./lib/runner.js --color
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.9.16/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.16/x64/lib
    GITHUB_TOKEN: ***
    GITHUB_REPOSITORY: nbost130/auto-build-Ender-3-Pro
    GITHUB_ACTOR: nbost130
Invalid or unexpected token
Error: Process completed with exit code 1.

**Comment by zisismaras** [comment]
Hi,

It seems there is a syntax error on your build file on line 56

```js
["BLTOUCH_DELAY", 500"], //remove the extra " after 500
```

As a tip, if you are able, try to use an editor that can highlight errors like these (like [vs code](https://code.visualstudio.com/) or anything you want)

There are also some issues with the configuration:

Enabling options that don't take an extra value should be defined as a single string `""` not inside an array `[]`
like this:
```js
["Z_SAFE_HOMING"] //should be just "Z_SAFE_HOMING"
["PREHEAT_1_TEMP_HOTEND", 205] //this is good
```
Fixing these will allow marlin to start building and you should start getting meaningful errors from marlin itself if your configuration is wrong.
