### ISSUE TITLE
marlin_auto_build stopped working

### ISSUE THREAD

**Issue by KamensekD** [zisismaras/marlin_auto_build#5]
Hello!

Unfortunately marlin_auto_build stopped working about a week ago.
First I thought it was problem with my configurations, but then I saw it also stopped working on your https://github.com/zisismaras/ender_3_4.2.2_firmware/actions repository.

I hope You can find some time to possibly fix it if it is not too big of an issue...

Best Regards,
Dejan

**Comment by zisismaras** [comment]
Hello,

Marlin recently released 2.1.1.1 but they have not published the default configurations yet so all the builds are failing.
It should probably start working again soon when they release the default configs.

I'll take a look soon to make it show a proper message instead of crashing.

**Comment by zisismaras** [comment]
They should be working again. Feel free to close if everything is ok

**Comment by KamensekD** [comment]
Hello!

Great news. It seems to work again for nightly release.
I thought it was a problem with marlin_auto_build, because no matter what I tried, I couldn't make any successfull build;
I wanted to at least use older Marlin version, that worked before, but couldn't do it.
If I understand correctly it is possible to build a specific Marlin release version, right?

What should I change in my configuration if, for example, I wanted to build release 2.0.9.7 instead of latest:
https://github.com/KamensekD/Ender-3_PRO_v4.2.2_Marlin_firmware/blob/master/builds/base.js

Thanx and Best Regards,
Dejan

**Comment by KamensekD** [comment]
> Hello,
> 
> Marlin recently released 2.1.1.1 but they have not published the default configurations yet so all the builds are failing. It should probably start working again soon when they release the default configs.
> 
> I'll take a look soon to make it show a proper message instead of crashing.

I'm very confuzed about Marin versions. Why is marlin_auto_build downloading 2.1.1.1 as stable? Isn't 2.1.2.1 latest?
https://github.com/MarlinFirmware/Marlin/releases?page=2

**Comment by KamensekD** [comment]
I guess marlin_auto_build downloads 2.1.1.1 as latest stable because it is listed on top of https://github.com/MarlinFirmware/Marlin/releases

Actual latest stable 2.1.x release is 2.1.2.1:
https://github.com/MarlinFirmware/Marlin/tree/2.1.x
https://github.com/MarlinFirmware/Marlin/releases/latest
https://github.com/MarlinFirmware/Configurations/releases/latest

It seems that because some changes for release 2.1.1.1 ("Update for compatibility with PlatformIO 6") were made later then any changes for 2.1.2.1, marlin_auto_build wrongly thinks that 2.1.1.1 is latest release. There are no default configurations for 2.1.1.1 (and probably won't be any) building stable always fails.

**Comment by KamensekD** [comment]
I found and solved the problem in my fork. I sent You pull request to fix it in yours, too. Regards, Dejan
